# Generated by Django 3.2.17 on 2023-02-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_workout', models.CharField(max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_fk', to='core.section')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_fk', to='core.workout')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='section_workout_mtm', through='core.Section_Workout', to='core.Workout'),
        ),
    ]
